language : cpp
sudo : enabled
dist : trusty
os : 
  - linux
  - osx
compiler:
  - clang
  - gcc
script:
   - mkdir build
   - cd build
   - cmake ../
   - cmake --build .
   - cd Tests
   - ./test_correctness
   - ./test_performance